import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Appbar } from "./components/Appbar";
import { cn } from "./utils/classNameMerge";
import { ClerkProvider } from "@clerk/nextjs";
import { Providers } from "./components/Providers";
import { Toaster } from "sonner";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "AssetXchange",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ClerkProvider>
        <Providers>
          <body
            className={cn(
              "h-screen font-sans antialiased grainy",
              inter.className
            )}
          >
            <Appbar />
            <Toaster position="bottom-right" richColors />
            {children}
          </body>
        </Providers>
      </ClerkProvider>
    </html>
  );
}
